### ISSUE TITLE
Content to style not matching what is described in the paper

### ISSUE THREAD

**Issue by neermat-iitk** [songrise/Artist#5]
Hi,

I'm trying to understand the content-to-style injection (for content-aware style generation) described in your paper. I've noticed that the code implementation seems to differ from what's described in the paper:

1. The content-to-style (c2s) injection appears to only affect self-attention and not cross-attention, as shown in this code section: https://github.com/songrise/Artist/blob/62909ba59c66714136e7cda7b4e64d59b5fb150e/models/attn_injection.py#L445-L453

2. The implementation copies values (instead of queries) from the content delegation to the style delegation's query component, as seen here:
https://github.com/songrise/Artist/blob/62909ba59c66714136e7cda7b4e64d59b5fb150e/models/attn_injection.py#L202-L210

Could you please clarify if these observations are correct, or am I misinterpreting something?

**Comment by songrise** [comment]
Hi, thanks for your question. I have checked the issue. For a short answer, you are right, the code and the arxiv paper has some discrepancies. This is mainly because this is a WIP project, so the code may contain some new changes. I will update the new paper soon. 

Additionaly, the current impl may not reproduce the examples in the paper, and it may have worse result on certain prompts. I will upload the code soon. You will be able to reproduce the the following results then.  
![image](https://github.com/user-attachments/assets/3d6c2080-0912-4d85-97f7-d29538487a0c)

**Comment by neermat-iitk** [comment]
Got it. Thanks for answering.
